//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace manajemen_inventaris.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Ini merupakan deskripsi paket 1")]
        public string des_paket1 {
            get {
                return ((string)(this["des_paket1"]));
            }
            set {
                this["des_paket1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Ini merupakan deskripsi paket 2")]
        public string des_paket2 {
            get {
                return ((string)(this["des_paket2"]));
            }
            set {
                this["des_paket2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Ini merupakan deskripsi paket 3")]
        public string des_paket3 {
            get {
                return ((string)(this["des_paket3"]));
            }
            set {
                this["des_paket3"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("mauthai")]
        public string pass {
            get {
                return ((string)(this["pass"]));
            }
            set {
                this["pass"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int harga_paket1 {
            get {
                return ((int)(this["harga_paket1"]));
            }
            set {
                this["harga_paket1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int harga_paket2 {
            get {
                return ((int)(this["harga_paket2"]));
            }
            set {
                this["harga_paket2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int harga_paket3 {
            get {
                return ((int)(this["harga_paket3"]));
            }
            set {
                this["harga_paket3"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Paket1")]
        public string nama_paket1 {
            get {
                return ((string)(this["nama_paket1"]));
            }
            set {
                this["nama_paket1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Paket2")]
        public string nama_paket2 {
            get {
                return ((string)(this["nama_paket2"]));
            }
            set {
                this["nama_paket2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Paket3")]
        public string nama_paket3 {
            get {
                return ((string)(this["nama_paket3"]));
            }
            set {
                this["nama_paket3"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3")]
        public string waktu {
            get {
                return ((string)(this["waktu"]));
            }
            set {
                this["waktu"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int antrian {
            get {
                return ((int)(this["antrian"]));
            }
            set {
                this["antrian"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Ini merupakan deskripsi paket 4")]
        public string des_paket4 {
            get {
                return ((string)(this["des_paket4"]));
            }
            set {
                this["des_paket4"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Ini merupakan deskripsi paket 5")]
        public string des_paket5 {
            get {
                return ((string)(this["des_paket5"]));
            }
            set {
                this["des_paket5"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Ini merupakan deskripsi paket 6")]
        public string des_paket6 {
            get {
                return ((string)(this["des_paket6"]));
            }
            set {
                this["des_paket6"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Ini merupakan deskripsi paket 7")]
        public string des_paket7 {
            get {
                return ((string)(this["des_paket7"]));
            }
            set {
                this["des_paket7"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Ini merupakan deskripsi paket 8")]
        public string des_paket8 {
            get {
                return ((string)(this["des_paket8"]));
            }
            set {
                this["des_paket8"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Ini merupakan deskripsi paket 9")]
        public string des_paket9 {
            get {
                return ((string)(this["des_paket9"]));
            }
            set {
                this["des_paket9"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int harga_paket4 {
            get {
                return ((int)(this["harga_paket4"]));
            }
            set {
                this["harga_paket4"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int harga_paket5 {
            get {
                return ((int)(this["harga_paket5"]));
            }
            set {
                this["harga_paket5"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int harga_paket6 {
            get {
                return ((int)(this["harga_paket6"]));
            }
            set {
                this["harga_paket6"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int harga_paket7 {
            get {
                return ((int)(this["harga_paket7"]));
            }
            set {
                this["harga_paket7"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int harga_paket8 {
            get {
                return ((int)(this["harga_paket8"]));
            }
            set {
                this["harga_paket8"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int harga_paket9 {
            get {
                return ((int)(this["harga_paket9"]));
            }
            set {
                this["harga_paket9"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Paket 4")]
        public string nama_paket4 {
            get {
                return ((string)(this["nama_paket4"]));
            }
            set {
                this["nama_paket4"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Paket 5")]
        public string nama_paket5 {
            get {
                return ((string)(this["nama_paket5"]));
            }
            set {
                this["nama_paket5"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Paket 6")]
        public string nama_paket6 {
            get {
                return ((string)(this["nama_paket6"]));
            }
            set {
                this["nama_paket6"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Paket 7")]
        public string nama_paket7 {
            get {
                return ((string)(this["nama_paket7"]));
            }
            set {
                this["nama_paket7"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Paket 8")]
        public string nama_paket8 {
            get {
                return ((string)(this["nama_paket8"]));
            }
            set {
                this["nama_paket8"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Paket 9")]
        public string nama_paket9 {
            get {
                return ((string)(this["nama_paket9"]));
            }
            set {
                this["nama_paket9"] = value;
            }
        }
    }
}
